// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlZJFpV4ApjkaQE0tH3P_VfSmK9PHgihk',
    appId: '1:534367058264:web:a6b3fa5bfb58f186a7cd2d',
    messagingSenderId: '534367058264',
    projectId: 'volunteer-community-c691d',
    authDomain: 'volunteer-community-c691d.firebaseapp.com',
    databaseURL: 'https://volunteer-community-c691d-default-rtdb.firebaseio.com',
    storageBucket: 'volunteer-community-c691d.appspot.com',
    measurementId: 'G-0HDWR98XPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDosFDuw0rjS5jMHcDuQlkzeV8WSTYrqS0',
    appId: '1:534367058264:android:7107821a4652e7ada7cd2d',
    messagingSenderId: '534367058264',
    projectId: 'volunteer-community-c691d',
    databaseURL: 'https://volunteer-community-c691d-default-rtdb.firebaseio.com',
    storageBucket: 'volunteer-community-c691d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe5wUOR-RvquYUF27NjvWFRwc2TSJj9PI',
    appId: '1:534367058264:ios:1fa4652cb6e9b5eaa7cd2d',
    messagingSenderId: '534367058264',
    projectId: 'volunteer-community-c691d',
    databaseURL: 'https://volunteer-community-c691d-default-rtdb.firebaseio.com',
    storageBucket: 'volunteer-community-c691d.appspot.com',
    iosClientId: '534367058264-nangd6oa31bhpn5tl72c06e7brfblb9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationProgectV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe5wUOR-RvquYUF27NjvWFRwc2TSJj9PI',
    appId: '1:534367058264:ios:1fa4652cb6e9b5eaa7cd2d',
    messagingSenderId: '534367058264',
    projectId: 'volunteer-community-c691d',
    databaseURL: 'https://volunteer-community-c691d-default-rtdb.firebaseio.com',
    storageBucket: 'volunteer-community-c691d.appspot.com',
    iosClientId: '534367058264-nangd6oa31bhpn5tl72c06e7brfblb9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationProgectV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlZJFpV4ApjkaQE0tH3P_VfSmK9PHgihk',
    appId: '1:534367058264:web:856bc8da89c3f38fa7cd2d',
    messagingSenderId: '534367058264',
    projectId: 'volunteer-community-c691d',
    authDomain: 'volunteer-community-c691d.firebaseapp.com',
    databaseURL: 'https://volunteer-community-c691d-default-rtdb.firebaseio.com',
    storageBucket: 'volunteer-community-c691d.appspot.com',
    measurementId: 'G-2F81JZ576Z',
  );

}